[CmdletBinding(SupportsShouldProcess = $true, ConfirmImpact = 'High')]
param(
    [Parameter(Mandatory = $true)]
    [string]$ValidatedConfigPath,

    [Parameter(Mandatory = $true)]
    [ValidateSet('WriteOnly', 'RestartBE200')]
    [string]$Mode,

    [Parameter()]
    [System.Management.Automation.PSCredential]$Credential,

    [Parameter()]
    [string]$Username = 'admin',

    [Parameter()]
    [string]$Password,

    [Parameter()]
    [string]$ResultCsvPath,

    [Parameter()]
    [string]$ResultJsonPath,

    [Parameter()]
    [string]$RollbackCsvPath,

    [Parameter()]
    [string]$RollbackJsonPath,

    [Parameter()]
    [string]$TranscriptPath
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

Import-Module (Join-Path $PSScriptRoot 'internal\BE200Toolkit.Common.psm1') -Force

<#
.SYNOPSIS
Applies validated Intel BE200 advanced-property changes.

.DESCRIPTION
This script consumes the validated per-target config generated by
validate-be200-config.ps1 and applies only rows where Apply=TRUE.

Execution modes:
- WriteOnly: writes advanced-property values with -NoRestart only
- RestartBE200: writes values with -NoRestart and then restarts only the exact
  allowlisted BE200 adapter(s) touched on that target

Safety rules:
- exact target allowlist only
- exact BE200 adapter allowlist only
- skip on ambiguity, never guess
- export rollback data only; do not auto-rollback

Use -WhatIf for a dry-run path before any real apply attempt.
#>

$validatedRows = @(
    Import-Csv -Path $ValidatedConfigPath |
        Where-Object { ConvertTo-BE200Boolean -Value $_.Apply }
)

if ($validatedRows.Count -eq 0) {
    throw 'The validated config did not contain any Apply=TRUE rows.'
}

$effectiveCredential = Resolve-BE200Credential -Credential $Credential -Username $Username -Password $Password

if (-not $ResultCsvPath) {
    $ResultCsvPath = New-BE200OutputFilePath -Category 'csv' -BaseName 'be200-apply-results' -Extension 'csv'
}

if (-not $ResultJsonPath) {
    $ResultJsonPath = New-BE200OutputFilePath -Category 'json' -BaseName 'be200-apply-results' -Extension 'json'
}

function Invoke-BE200ShouldProcess {
    param(
        [string]$Target,
        [string]$Operation
    )

    if ($null -ne $PSCmdlet) {
        try {
            return $PSCmdlet.ShouldProcess($Target, $Operation)
        }
        catch {
            return $true
        }
    }

    return $true
}

if (-not $RollbackCsvPath) {
    $RollbackCsvPath = New-BE200OutputFilePath -Category 'csv' -BaseName 'be200-rollback-data' -Extension 'csv'
}

if (-not $RollbackJsonPath) {
    $RollbackJsonPath = New-BE200OutputFilePath -Category 'json' -BaseName 'be200-rollback-data' -Extension 'json'
}

if (-not $TranscriptPath) {
    $TranscriptPath = New-BE200OutputFilePath -Category 'transcripts' -BaseName 'apply-be200-config' -Extension 'log'
}

$resultRows = New-Object System.Collections.Generic.List[object]
$rollbackRows = New-Object System.Collections.Generic.List[object]
$groupedTargets = $validatedRows | Group-Object EffectiveTargetIP
$allowedInterfaceDescriptions = Get-BE200AllowedInterfaceDescriptions
$transcriptStarted = $false

if ($env:BE200_NONINTERACTIVE -eq '1') {
    $ConfirmPreference = 'None'
}

try {
    try {
        Start-Transcript -Path $TranscriptPath -Force | Out-Null
        $transcriptStarted = $true
    }
    catch {
        Write-Warning ("Transcript could not be started. Continuing without transcript capture. {0}" -f $_.Exception.Message)
    }

    Write-BE200Section -Message ('Applying BE200 advanced-property config ({0})' -f $Mode)

    foreach ($targetGroup in $groupedTargets) {
        $target = $targetGroup.Name
        $rowsForTarget = @($targetGroup.Group)
        $performApply = if ($env:BE200_NONINTERACTIVE -eq '1' -or $ConfirmPreference -eq 'None') {
            $true
        }
        else {
            Invoke-BE200ShouldProcess `
                -Target $target `
                -Operation ('Apply {0} validated BE200 config row(s) in mode {1}' -f $rowsForTarget.Count, $Mode)
        }

        try {
            $remoteRows = Invoke-Command -ComputerName $target -Credential $effectiveCredential -ErrorAction Stop -ScriptBlock {
                param($Rows, $ExecutionMode, $PerformApply, $AllowedInterfaceDescriptions)

                if (
                    $AllowedInterfaceDescriptions -is [System.Collections.IEnumerable] -and
                    -not ($AllowedInterfaceDescriptions -is [string]) -and
                    @($AllowedInterfaceDescriptions).Count -eq 1 -and
                    @($AllowedInterfaceDescriptions)[0] -is [System.Collections.IEnumerable] -and
                    -not (@($AllowedInterfaceDescriptions)[0] -is [string])
                ) {
                    $AllowedInterfaceDescriptions = @(@($AllowedInterfaceDescriptions)[0])
                }

                function Join-ValueList {
                    param([object]$Value)

                    if ($null -eq $Value) {
                        return ''
                    }

                    if ($Value -is [string]) {
                        return $Value.Trim()
                    }

                    $items = @(
                        foreach ($item in $Value) {
                            if ($null -ne $item) {
                                $text = $item.ToString().Trim()
                                if ($text) {
                                    $text
                                }
                            }
                        }
                    )

                    return ($items -join '; ')
                }

                function Get-PropertyRecord {
                    param($AdapterName, $RegistryKeyword, $PropertyDisplayName)

                    $matches = @()
                    if ($RegistryKeyword) {
                        $matches = @(Get-NetAdapterAdvancedProperty -Name $AdapterName -RegistryKeyword $RegistryKeyword -AllProperties -ErrorAction SilentlyContinue)
                        if ($PropertyDisplayName) {
                            $matches = @($matches | Where-Object { $_.DisplayName -eq $PropertyDisplayName })
                        }
                    }
                    elseif ($PropertyDisplayName) {
                        $matches = @(Get-NetAdapterAdvancedProperty -Name $AdapterName -DisplayName $PropertyDisplayName -AllProperties -ErrorAction SilentlyContinue)
                    }

                    return @($matches)
                }

                function Resolve-BE200AdapterFromWlanInterface {
                    param(
                        [object[]]$Candidates,
                        [string]$InterfaceDescription
                    )

                    try {
                        $raw = & netsh wlan show interfaces 2>&1
                    }
                    catch {
                        return [pscustomobject]@{ Adapter = $null; Note = $null }
                    }

                    $text = ($raw | Out-String)
                    if (-not $text -or $text.Trim().Length -eq 0) {
                        return [pscustomobject]@{ Adapter = $null; Note = $null }
                    }

                    $blocks = $text -split '(?=\s+Name\s+:)'
                    foreach ($block in $blocks) {
                        $info = @{}
                        foreach ($line in ($block -split "`n")) {
                            if ($line -match '^\s+(.+?)\s+:\s+(.+)$') {
                                $info[$Matches[1].Trim()] = $Matches[2].Trim()
                            }
                        }

                        if (-not $info.ContainsKey('Name')) {
                            continue
                        }

                        if ($info.ContainsKey('Description') -and $info['Description'] -ne $InterfaceDescription) {
                            continue
                        }

                        $namedMatches = @($Candidates | Where-Object { $_.Name -eq $info['Name'] -and $_.InterfaceDescription -eq $InterfaceDescription })
                        if ($namedMatches.Count -eq 1) {
                            return [pscustomobject]@{
                                Adapter = $namedMatches[0]
                                Note    = ("Resolved via WLAN interface '{0}'." -f $info['Name'])
                            }
                        }
                    }

                    return [pscustomobject]@{ Adapter = $null; Note = $null }
                }

                function Resolve-BE200Adapter {
                    param(
                        [string]$InterfaceDescription,
                        [string[]]$AllowedInterfaceDescriptions
                    )

                    if ($AllowedInterfaceDescriptions -notcontains $InterfaceDescription) {
                        return [pscustomobject]@{
                            Adapter = $null
                            Note    = 'AdapterMatch was not allowlisted on the remote side.'
                        }
                    }

                    $matching = @(
                        Get-NetAdapter -ErrorAction SilentlyContinue |
                            Where-Object {
                                $_ -and
                                $_.InterfaceDescription -eq $InterfaceDescription -and
                                $_.Status -ne 'Not Present'
                            }
                    )

                    foreach ($preferredStatus in @('Up', 'Disconnected')) {
                        $preferredMatches = @($matching | Where-Object { $_.Status -eq $preferredStatus })
                        if ($preferredMatches.Count -eq 1) {
                            return [pscustomobject]@{
                                Adapter = $preferredMatches[0]
                                Note    = $null
                            }
                        }

                        if ($preferredMatches.Count -gt 1) {
                            $wlanSelection = Resolve-BE200AdapterFromWlanInterface -Candidates $preferredMatches -InterfaceDescription $InterfaceDescription
                            if ($null -ne $wlanSelection.Adapter) {
                                return $wlanSelection
                            }

                            return [pscustomobject]@{
                                Adapter = $null
                                Note    = ("Multiple adapters matched allowlisted InterfaceDescription '{0}' with Status '{1}'. Skipping to avoid ambiguity." -f $InterfaceDescription, $preferredStatus)
                            }
                        }
                    }

                    if ($matching.Count -eq 1) {
                        return [pscustomobject]@{
                            Adapter = $matching[0]
                            Note    = $null
                        }
                    }

                    if ($matching.Count -gt 1) {
                        $wlanSelection = Resolve-BE200AdapterFromWlanInterface -Candidates $matching -InterfaceDescription $InterfaceDescription
                        if ($null -ne $wlanSelection.Adapter) {
                            return $wlanSelection
                        }

                        return [pscustomobject]@{
                            Adapter = $null
                            Note    = ("Multiple adapters matched allowlisted InterfaceDescription '{0}' with non-preferred statuses. Skipping to avoid ambiguity." -f $InterfaceDescription)
                        }
                    }

                    return [pscustomobject]@{
                        Adapter = $null
                        Note    = 'The allowlisted BE200 adapter was not found on the remote target.'
                    }
                }

                $computerName = $env:COMPUTERNAME
                $pendingResults = New-Object System.Collections.Generic.List[object]
                $restartQueue = New-Object System.Collections.Generic.HashSet[string]

                foreach ($row in $Rows) {
                    $notes = New-Object System.Collections.Generic.List[string]
                    $applySucceeded = $false
                    $restartAttempted = $false
                    $restartSucceeded = $null

                    $adapterResolution = Resolve-BE200Adapter -InterfaceDescription $row.AdapterMatch -AllowedInterfaceDescriptions $AllowedInterfaceDescriptions
                    $adapter = $adapterResolution.Adapter
                    if (-not $adapter) {
                        [void]$pendingResults.Add([pscustomobject]@{
                            ComputerName          = $computerName
                            TargetIP              = $row.EffectiveTargetIP
                            AdapterName           = $row.AdapterMatch
                            PropertyDisplayName   = $row.PropertyDisplayName
                            RegistryKeyword       = $row.RegistryKeyword
                            OriginalValue         = $null
                            OriginalRegistryValue = $null
                            TargetValue           = $row.TargetValue
                            FinalValue            = $null
                            FinalRegistryValue    = $null
                            ApplyAttempted        = $PerformApply
                            ApplySucceeded        = $false
                            VerificationSucceeded = $false
                            ExecutionMode         = $ExecutionMode
                            TargetValueType       = $row.TargetValueType
                            RestartAttempted      = $restartAttempted
                            RestartSucceeded      = $restartSucceeded
                            Notes                 = $adapterResolution.Note
                        })
                        continue
                    }

                    $propertyMatches = @(Get-PropertyRecord -AdapterName $adapter.Name -RegistryKeyword $row.RegistryKeyword -PropertyDisplayName $row.PropertyDisplayName)
                    if ($propertyMatches.Count -eq 0) {
                        [void]$pendingResults.Add([pscustomobject]@{
                            ComputerName          = $computerName
                            TargetIP              = $row.EffectiveTargetIP
                            AdapterName           = $adapter.Name
                            PropertyDisplayName   = $row.PropertyDisplayName
                            RegistryKeyword       = $row.RegistryKeyword
                            OriginalValue         = $null
                            OriginalRegistryValue = $null
                            TargetValue           = $row.TargetValue
                            FinalValue            = $null
                            FinalRegistryValue    = $null
                            ApplyAttempted        = $PerformApply
                            ApplySucceeded        = $false
                            VerificationSucceeded = $false
                            ExecutionMode         = $ExecutionMode
                            TargetValueType       = $row.TargetValueType
                            RestartAttempted      = $restartAttempted
                            RestartSucceeded      = $restartSucceeded
                            Notes                 = 'The validated property was not found on the remote target.'
                        })
                        continue
                    }

                    if ($propertyMatches.Count -gt 1) {
                        [void]$pendingResults.Add([pscustomobject]@{
                            ComputerName          = $computerName
                            TargetIP              = $row.EffectiveTargetIP
                            AdapterName           = $adapter.Name
                            PropertyDisplayName   = $row.PropertyDisplayName
                            RegistryKeyword       = $row.RegistryKeyword
                            OriginalValue         = $null
                            OriginalRegistryValue = $null
                            TargetValue           = $row.TargetValue
                            FinalValue            = $null
                            FinalRegistryValue    = $null
                            ApplyAttempted        = $PerformApply
                            ApplySucceeded        = $false
                            VerificationSucceeded = $false
                            ExecutionMode         = $ExecutionMode
                            TargetValueType       = $row.TargetValueType
                            RestartAttempted      = $restartAttempted
                            RestartSucceeded      = $restartSucceeded
                            Notes                 = 'The validated property matched more than one remote property. Skipping to avoid ambiguity.'
                        })
                        continue
                    }

                    $before = $propertyMatches[0]
                    $resultRow = [pscustomobject]@{
                        ComputerName          = $computerName
                        TargetIP              = $row.EffectiveTargetIP
                        AdapterName           = $adapter.Name
                        PropertyDisplayName   = if ($before.DisplayName) { $before.DisplayName } else { $row.PropertyDisplayName }
                        RegistryKeyword       = if ($before.RegistryKeyword) { $before.RegistryKeyword } else { $row.RegistryKeyword }
                        OriginalValue         = $before.DisplayValue
                        OriginalRegistryValue = Join-ValueList -Value $before.RegistryValue
                        TargetValue           = $row.TargetValue
                        FinalValue            = $null
                        FinalRegistryValue    = $null
                        ApplyAttempted        = $PerformApply
                        ApplySucceeded        = $false
                        VerificationSucceeded = $false
                        ExecutionMode         = $ExecutionMode
                        TargetValueType       = $row.TargetValueType
                        RestartAttempted      = $restartAttempted
                        RestartSucceeded      = $restartSucceeded
                        Notes                 = ''
                    }

                    if (-not $PerformApply) {
                        $resultRow.Notes = 'Dry-run / WhatIf: no change applied.'
                        [void]$pendingResults.Add($resultRow)
                        continue
                    }

                    try {
                        if ($row.TargetValueType -eq 'RegistryValue') {
                            $registryValues = @(
                                foreach ($piece in ($row.TargetValue -split '\s*,\s*')) {
                                    if (-not [string]::IsNullOrWhiteSpace($piece)) {
                                        [int]$piece.Trim()
                                    }
                                }
                            )

                            Set-NetAdapterAdvancedProperty -Name $adapter.Name -RegistryKeyword $resultRow.RegistryKeyword -RegistryValue $registryValues -NoRestart -ErrorAction Stop
                            $applySucceeded = $true
                        }
                        elseif ($row.TargetValueType -eq 'DisplayValue') {
                            if (-not $resultRow.PropertyDisplayName) {
                                throw 'The property does not expose a DisplayName, so DisplayValue apply is not safe.'
                            }

                            Set-NetAdapterAdvancedProperty -Name $adapter.Name -DisplayName $resultRow.PropertyDisplayName -DisplayValue $row.TargetValue -NoRestart -ErrorAction Stop
                            $applySucceeded = $true
                        }
                        else {
                            throw 'TargetValueType was not resolved to DisplayValue or RegistryValue.'
                        }

                        if ($ExecutionMode -eq 'RestartBE200') {
                            [void]$restartQueue.Add($adapter.Name)
                        }
                    }
                    catch {
                        [void]$notes.Add(('Apply failed: {0}' -f $_.Exception.Message))
                    }

                    $resultRow.ApplySucceeded = $applySucceeded
                    $resultRow.Notes = ($notes -join ' ')
                    [void]$pendingResults.Add($resultRow)
                }

                if ($PerformApply -and $ExecutionMode -eq 'RestartBE200' -and $restartQueue.Count -gt 0) {
                    foreach ($adapterName in $restartQueue) {
                        $restartOk = $false
                        $restartMessage = $null
                        try {
                            Restart-NetAdapter -Name $adapterName -Confirm:$false -ErrorAction Stop
                            $restartOk = $true
                        }
                        catch {
                            $restartMessage = $_.Exception.Message
                        }

                        foreach ($resultRow in $pendingResults | Where-Object { $_.AdapterName -eq $adapterName }) {
                            $resultRow.RestartAttempted = $true
                            $resultRow.RestartSucceeded = $restartOk
                            if (-not $restartOk) {
                                if ($resultRow.Notes) {
                                    $resultRow.Notes = $resultRow.Notes + ' '
                                }
                                $resultRow.Notes = $resultRow.Notes + ('Restart failed: {0}' -f $restartMessage)
                            }
                        }
                    }
                }

                foreach ($resultRow in $pendingResults) {
                    $afterMatches = @(Get-PropertyRecord -AdapterName $resultRow.AdapterName -RegistryKeyword $resultRow.RegistryKeyword -PropertyDisplayName $resultRow.PropertyDisplayName)
                    if ($afterMatches.Count -eq 1) {
                        $after = $afterMatches[0]
                        $resultRow.FinalValue = $after.DisplayValue
                        $resultRow.FinalRegistryValue = Join-ValueList -Value $after.RegistryValue

                        if ($resultRow.ApplyAttempted -and $resultRow.ApplySucceeded) {
                            if ($resultRow.TargetValueType -eq 'RegistryValue') {
                                $normalizedTarget = Join-ValueList -Value ($resultRow.TargetValue -split '\s*,\s*')
                                $resultRow.VerificationSucceeded = ($resultRow.FinalRegistryValue -eq $normalizedTarget)
                            }
                            elseif ($resultRow.TargetValueType -eq 'DisplayValue') {
                                $resultRow.VerificationSucceeded = ($resultRow.FinalValue -eq $resultRow.TargetValue)
                            }
                        }
                    }
                }

                return @($pendingResults.ToArray())
            } -ArgumentList @($rowsForTarget, $Mode, $performApply, (, $allowedInterfaceDescriptions))

            foreach ($remoteRow in @($remoteRows)) {
                [void]$resultRows.Add($remoteRow)
                [void]$rollbackRows.Add([pscustomobject]@{
                    ComputerName         = $remoteRow.ComputerName
                    TargetIP             = $remoteRow.TargetIP
                    AdapterName          = $remoteRow.AdapterName
                    PropertyDisplayName  = $remoteRow.PropertyDisplayName
                    RegistryKeyword      = $remoteRow.RegistryKeyword
                    RollbackDisplayValue = $remoteRow.OriginalValue
                    RollbackRegistryValue = $remoteRow.OriginalRegistryValue
                    Notes                = 'Rollback data only. No automatic rollback is performed by this toolkit.'
                })
            }
        }
        catch {
            foreach ($row in $rowsForTarget) {
                [void]$resultRows.Add([pscustomobject]@{
                    ComputerName          = $null
                    TargetIP              = $target
                    AdapterName           = $row.AdapterMatch
                    PropertyDisplayName   = $row.PropertyDisplayName
                    RegistryKeyword       = $row.RegistryKeyword
                    OriginalValue         = $null
                    OriginalRegistryValue = $null
                    TargetValue           = $row.TargetValue
                    FinalValue            = $null
                    FinalRegistryValue    = $null
                    ApplyAttempted        = $performApply
                    ApplySucceeded        = $false
                    VerificationSucceeded = $false
                    ExecutionMode         = $Mode
                    TargetValueType       = $row.TargetValueType
                    RestartAttempted      = ($performApply -and $Mode -eq 'RestartBE200')
                    RestartSucceeded      = $false
                    Notes                 = ('Remote apply failed before row execution: {0}' -f $_.Exception.Message)
                })
            }
        }
    }

    Export-BE200Csv -InputObject @($resultRows.ToArray()) -Path $ResultCsvPath
    Export-BE200Json -InputObject @($resultRows.ToArray()) -Path $ResultJsonPath
    Export-BE200Csv -InputObject @($rollbackRows.ToArray()) -Path $RollbackCsvPath
    Export-BE200Json -InputObject @($rollbackRows.ToArray()) -Path $RollbackJsonPath

    Write-Host
    Write-Host 'Apply summary:' -ForegroundColor Green
    @($resultRows.ToArray()) |
        Sort-Object TargetIP, AdapterName, RegistryKeyword, PropertyDisplayName |
        Format-Table TargetIP, AdapterName, PropertyDisplayName, RegistryKeyword, ApplyAttempted, ApplySucceeded, VerificationSucceeded, ExecutionMode -AutoSize

    Write-Host
    Write-Host ("Apply results CSV: {0}" -f $ResultCsvPath) -ForegroundColor Green
    Write-Host ("Apply results JSON: {0}" -f $ResultJsonPath) -ForegroundColor Green
    Write-Host ("Rollback CSV:      {0}" -f $RollbackCsvPath) -ForegroundColor Green
    Write-Host ("Rollback JSON:     {0}" -f $RollbackJsonPath) -ForegroundColor Green
    Write-Host ("Transcript log:    {0}" -f $TranscriptPath) -ForegroundColor Green
}
finally {
    if ($transcriptStarted) {
        try {
            Stop-Transcript | Out-Null
        }
        catch {
        }
    }
}
